name: Download Artifact from Another Repo

on: workflow_dispatch  # Or any other event that suits your workflow needs

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
      - id : get_run_id
        run: |
          response = $(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ARTIFACT_REPO}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Ash210611/silverton-dataops-brutesquad-exapmle/actions/artifacts?per_page=1)

          # Extract the run_id of the latest workflow run
          # run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')

      # - name: Download github_branch
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: github_branch
      #     github-token : ${{ secrets.ARTIFACT_REPO}}
      #     repository : Ash210611/silverton-dataops-brutesquad-exapmle
      #     run-id : ${{ steps.get_run_id.outputs.run_id }}
