name: Download Artifact from Another Repo

on: workflow_dispatch  # Or any other event that suits your workflow needs

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Artifact Information
        id: get_artifact_info
        run: |
          response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ARTIFACT_REPO }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Ash210611/silverton-dataops-brutesquad-example/actions/artifacts?per_page=1)
          echo "$response" | jq
          artifact_id=$(echo "$response" | jq -r '.artifacts[0].id')
          # echo "::set-output name=artifact_id::$artifact_id"

      - name: Download Artifact
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ARTIFACT_REPO }}" \
          "https://api.github.com/repos/Ash210611/silverton-dataops-brutesquad-example/actions/artifacts/${{ steps.get_artifact_info.outputs.artifact_id }}/zip" \
          -o artifact.zip
