name: Download Artifact from Another Repo

on: workflow_dispatch  # Or any other event that suits your workflow needs

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Artifact Information
        id: get_artifact_info
        run: |
          response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ARTIFACT_REPO }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Ash210611/silverton-dataops-brutesquad-exapmle/actions/artifacts?per_page=1)
          echo "$response" | jq
          run_id=$(echo "$response" | jq -r '.artifacts[0].workflow_run.id')
          echo "Latest run id is : $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
         name: selectedbranch
         github-token : ${{ secrets.ARTIFACT_REPO}}
         repository : Ash210611/silverton-dataops-brutesquad-exapmle
         run-id : ${{ steps.get_artifact_info.outputs.run_id }}
         # path: ./

      - name: List files in the directory
        run: ls -la

      # - name: Unzip Artifact (if needed)
      #   run: unzip selectedbranch -d ./

      - name: Get the Value
        id : get_branch_value
        run: |
          branch_value = $(cat selected-branch.txt)
          echo "branch_value=${branch_value}"
          echo "branch=${branch_value}" >> $GITHUB_OUTPUT
