name: Download Artifact from Another Repo

on: workflow_dispatch  # Or any other event that suits your workflow needs

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.ARTIFACT_REPO}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -o artifacts.json \
          https://api.github.com/repos/Ash210611/silverton-dataops-brutesquad-exapmle/actions/artifacts

      # - name: Download Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: selected-branch
      #     repo: Ash210611/silverton-datops-brutesquad-example
      #     token: ${{ secrets.ARTIFACTS_PAT }}

