name: "Example Solution Workflow" 

on:
  workflow_dispatch:
    inputs:
      TDV_Environment:
        type: choice
        description: "Select the environment of the TDV server"
        options:
          - dev
          - TEST
          - ITE
          - PROD
        default:
          dev

jobs:
  build:
    # runs-on: MA-Analytics-Runner
    runs-on : ubuntu-latest
    steps:
      - name: Checkout Solution Repository
        uses: actions/checkout@v4
        with:
          repository: Ash210611/silverton-solution-brutesquad-example
          path: solution-repo

      # Set up environment-specific variables
      - name: Set Environment Variables
        run: echo "CONFIG_FILE=${{ inputs.TDV_Environment }}.liquibase" >> $GITHUB_ENV

      - name: List Files in Source Directory
        run: ls -R solution-repo/.github/workflows

      # Copy the file from the solution repository to the workspace
      - name: Copy Configuration File
        run: cp solution-repo/.github/workflows/${{ env.CONFIG_FILE }} ${{ github.workspace }}/config

      - name: Verify Copied File
        run: cat ${{ github.workspace }}/config/${{ env.CONFIG_FILE }}

      - name: List Files in Working Directory
        run: ls -R ${{ github.workspace }}

      - name: List Files in Working Directory
        run: ls -R ${{ github.workspace }}/config

      # - uses: actions/checkout@v4
      - id: OPS-action
        uses: Ash210611/silverton-dataops-brutesquad-exapmle@main
        with: 
          TDV_USER: ${{ secrets.TDV_SERV_USER_DEV }}
          TDV_PASSWORD: ${{ secrets.TDV_SERV_PASSWORD_DEV }}
          TDV_ENV: ${{ inputs.TDV_Environment }}
          CONFIG_PATH: ${{ github.workspace }}/config/${{ env.CONFIG_FILE }}
